import type { CultureRegionKey } from "./culture-atlas";

export type LiteraryEvidenceLevel = "较高" | "中等" | "谨慎";
export type LiteraryPortraitReliability = "传世画像" | "后世绘像" | "暂无可靠画像";

export type LiteraryWork = {
  title: string;
  note?: string;
};

export type LiteraryPortrait = {
  src: string;
  alt: string;
  reliability: LiteraryPortraitReliability;
  note: string;
  sourceUrl?: string;
};

export type LiteraryFigure = {
  eraId: string;
  name: string;
  years: string;
  identity: string;
  works: LiteraryWork[];
  regionKey: CultureRegionKey;
  placeLabel: string;
  locationBasis: string;
  evidenceLevel: LiteraryEvidenceLevel;
  evidenceNote: string;
  brief: string;
  sourceUrls: string[];
  portrait: LiteraryPortrait;
};

const unavailablePortrait = (name: string, note = "目前未找到可确认为本人容貌的可靠传世画像；未采用现代想象图。"):
  LiteraryPortrait => ({
  src: "",
  alt: `${name}画像占位`,
  reliability: "暂无可靠画像",
  note,
});

const laterPortrait = (name: string, note = "常见形象多来自后世绘像，但本页尚未采用未经逐件核验的图像；未采用现代想象图。"):
  LiteraryPortrait => ({
  src: "",
  alt: `${name}画像占位`,
  reliability: "暂无可靠画像",
  note,
});

export const literaryFigures = [
  {
    eraId: "xia",
    name: "涂山氏女（传统归属）",
    years: "传说时代",
    identity: "上古歌谣传统人物",
    works: [{ title: "《候人歌》", note: "仅存“候人兮猗”；由《吕氏春秋》追记，非夏代同期文献" }],
    regionKey: "jianghuai",
    placeLabel: "淮河涂山（传统说）",
    locationBasis: "传说发生地；涂山地望存在争议",
    evidenceLevel: "谨慎",
    evidenceNote: "人物和歌辞属于后世文献保存的夏代传统，不宜视作考古证实的夏代诗人。",
    brief: "以一句等待之歌承载大禹婚姻传说，是上古歌谣记忆的象征性节点。",
    sourceUrls: [
      "https://www.ahhy.gov.cn/zjhy/lswh/lsrw/80744041.html",
      "https://ctext.org/lv-shi-chun-qiu/yin-chu/zh",
    ],
    portrait: unavailablePortrait("涂山氏女", "传说人物没有可靠画像；不应把现代影视或AI形象标成史实肖像。"),
  },
  {
    eraId: "shang",
    name: "殷墟贞人群体",
    years: "约前13—前11世纪",
    identity: "甲骨卜辞记录者群体",
    works: [{ title: "殷墟甲骨卜辞", note: "群体记录，非单一作者作品集" }],
    regionKey: "heartland",
    placeLabel: "安阳殷墟",
    locationBasis: "甲骨文主要出土地与晚商都邑",
    evidenceLevel: "较高",
    evidenceNote: "甲骨文字与出土地可核，但“贞人群体”不是现代意义上的诗人群体。",
    brief: "用可核的书写者群体呈现商代文字文化，避免为史料无载的诗人虚构姓名。",
    sourceUrls: ["https://www.chnmuseum.cn/zl/zlhg/201812/t20181220_32409.shtml"],
    portrait: unavailablePortrait("殷墟贞人群体", "群体成员没有可识别的个人画像。"),
  },
  {
    eraId: "western-zhou",
    name: "虢季子白",
    years: "约前9世纪",
    identity: "西周贵族、铭文主人",
    works: [{ title: "《虢季子白盘铭》", note: "铭文作者不详；子白是作器者与叙事主人" }],
    regionKey: "guanzhong",
    placeLabel: "宗周—洛水政治圈",
    locationBasis: "铭文所载受命及征战活动区",
    evidenceLevel: "较高",
    evidenceNote: "器物和铭文可靠，但不能把铭文执笔直接归给虢季子白。",
    brief: "盘铭四字成句且押韵，被中国国家博物馆称为藏在金文中的诗。",
    sourceUrls: ["https://www.chnmuseum.cn/zp/zpml/csp/202008/t20200826_247376.shtml"],
    portrait: unavailablePortrait("虢季子白"),
  },
  {
    eraId: "western-zhou",
    name: "尹吉甫（传统归属）",
    years: "约前9—前8世纪",
    identity: "西周卿士、传统诗人",
    works: [
      { title: "《崧高》", note: "传统归属" },
      { title: "《烝民》", note: "传统归属" },
    ],
    regionKey: "guanzhong",
    placeLabel: "周王室活动区",
    locationBasis: "主要政治活动地；具体地望取示意",
    evidenceLevel: "谨慎",
    evidenceNote: "《诗经》篇章的个人作者归属多来自传统说法，并非同期署名证据。",
    brief: "适合用来解释西周王室诗歌传统，但作品卡必须保留“传统归属”。",
    sourceUrls: ["https://ctext.org/book-of-poetry/decade-of-dang/zh"],
    portrait: unavailablePortrait("尹吉甫"),
  },
  {
    eraId: "eastern-zhou",
    name: "孔子",
    years: "前551—前479",
    identity: "思想家、教育家",
    works: [{ title: "《论语》", note: "由弟子及再传弟子辑录" }],
    regionKey: "heartland",
    placeLabel: "鲁国曲阜",
    locationBasis: "故里及主要讲学地",
    evidenceLevel: "较高",
    evidenceNote: "人物与主要活动可信；《论语》不是孔子亲笔著作。",
    brief: "作为先秦文教与经典传播的核心人物进入文学名人层，而非标为诗人。",
    sourceUrls: ["https://ctext.org/analects/zh"],
    portrait: {
      src: "/figures/confucius.jpg",
      alt: "孔子后世绘像",
      reliability: "后世绘像",
      note: "唐代以来传承的孔子图像系统，可作形象史参考，不等同于本人写真。",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Confucius_Tang_Dynasty.jpg",
    },
  },
  {
    eraId: "eastern-zhou",
    name: "庄周",
    years: "约前369—前286",
    identity: "思想家、散文家",
    works: [{ title: "《庄子·逍遥游》" }, { title: "《庄子·齐物论》" }],
    regionKey: "heartland",
    placeLabel: "宋国蒙地（传统说）",
    locationBasis: "传统籍贯；蒙地具体地望有讨论",
    evidenceLevel: "中等",
    evidenceNote: "庄周其人与核心篇章可据，但今本《庄子》并非全部出自庄周一人。",
    brief: "以寓言、想象和哲思塑造先秦散文高峰。",
    sourceUrls: ["https://ctext.org/zhuangzi/zh"],
    portrait: {
      src: "/figures/zhuangzi.jpg",
      alt: "庄周后世绘像",
      reliability: "后世绘像",
      note: "元代道教人物图像中的庄子形象，可作后世接受史材料。",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:%E7%8E%84%E9%96%80%E5%8D%81%E5%AD%90%E5%9C%96_%E8%8E%8A%E5%AD%90.jpg",
    },
  },
  {
    eraId: "eastern-zhou",
    name: "屈原",
    years: "约前340—前278",
    identity: "楚国诗人、政治家",
    works: [{ title: "《离骚》" }, { title: "《九歌》", note: "篇章形成与归属有学术讨论" }, { title: "《天问》" }],
    regionKey: "jianghuai",
    placeLabel: "楚地郢都—江汉",
    locationBasis: "任职与主要流放活动区域",
    evidenceLevel: "中等",
    evidenceNote: "生平主要依据《史记》；《楚辞》各篇归属的确定程度不同。",
    brief: "中国早期最重要的署名诗人之一，以楚辞开拓宏阔而个人化的抒情传统。",
    sourceUrls: [
      "https://ctext.org/datawiki.pl?if=gb&remap=gb&res=894522",
      "https://ctext.org/chu-ci/zh",
    ],
    portrait: {
      src: "/figures/qu-yuan.jpg",
      alt: "屈原后世绘像",
      reliability: "后世绘像",
      note: "明代陈洪绶系统的屈原形象，可作文学接受史参考。",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Qu_Yuan_Chen_Hongshou_2.jpg",
    },
  },
  {
    eraId: "eastern-zhou",
    name: "宋玉",
    years: "约前298—前222",
    identity: "楚辞作家、辞赋家",
    works: [{ title: "《九辩》", note: "传统归属" }, { title: "《风赋》", note: "传统归属" }],
    regionKey: "jianghuai",
    placeLabel: "楚国郢都文化圈",
    locationBasis: "传统主要活动地",
    evidenceLevel: "谨慎",
    evidenceNote: "宋玉生平材料稀少，传世作品归属多有争议。",
    brief: "作为楚辞向汉赋过渡的重要传统人物展示，不能将后世拟作全部归于其名下。",
    sourceUrls: ["https://ctext.org/chu-ci/nine-changes/zh"],
    portrait: laterPortrait("宋玉"),
  },
  {
    eraId: "qin",
    name: "李斯",
    years: "？—前208",
    identity: "政治家、散文家、书法史人物",
    works: [
      { title: "《谏逐客书》" },
      { title: "《泰山刻石》", note: "传为李斯撰书" },
      { title: "《琅邪台刻石》", note: "传为李斯撰书" },
    ],
    regionKey: "guanzhong",
    placeLabel: "咸阳",
    locationBasis: "主要任职地",
    evidenceLevel: "中等",
    evidenceNote: "人物和《谏逐客书》可靠；刻石撰书归属宜保留“传”。",
    brief: "秦代可核文学名人不宜强凑，李斯的政论文与刻石文字足以构成核心节点。",
    sourceUrls: [
      "https://www.dpm.org.cn/lemmas/243613.html",
      "https://www.dpm.org.cn/classify_detail/372418.html",
    ],
    portrait: laterPortrait("李斯"),
  },
  {
    eraId: "western-han",
    name: "司马相如",
    years: "约前179—前118",
    identity: "辞赋家",
    works: [{ title: "《子虚赋》" }, { title: "《上林赋》" }, { title: "《长门赋》", note: "作者归属有争议" }],
    regionKey: "southwest",
    placeLabel: "蜀郡成都",
    locationBasis: "籍贯与早年活动地",
    evidenceLevel: "中等",
    evidenceNote: "人物与大赋成就可据；《长门赋》归属需提示争议。",
    brief: "铺陈宏富的汉大赋代表，也连接了蜀地与长安宫廷文化。",
    sourceUrls: ["https://www.dpm.org.cn/lemmas/244919.html"],
    portrait: laterPortrait("司马相如"),
  },
  {
    eraId: "western-han",
    name: "司马迁",
    years: "约前145—约前86",
    identity: "史学家、散文家",
    works: [{ title: "《史记》" }, { title: "《报任安书》" }],
    regionKey: "guanzhong",
    placeLabel: "夏阳龙门—长安",
    locationBasis: "传统籍贯与主要任职地",
    evidenceLevel: "较高",
    evidenceNote: "生年存在不同说法，地图采用常见约数。",
    brief: "以纪传体叙事和鲜明人物书写深刻影响后世史学与文学。",
    sourceUrls: [
      "https://ctext.org/datawiki.pl?if=gb&remap=gb&res=760586",
      "https://ctext.org/shiji/zh",
    ],
    portrait: {
      src: "/figures/sima-qian.jpg",
      alt: "司马迁后世绘像",
      reliability: "后世绘像",
      note: "传统司马迁画像，可作后世形象参考，不等同于本人写真。",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Si_maqian.jpg",
    },
  },
  {
    eraId: "western-han",
    name: "刘向",
    years: "前79—前8",
    identity: "经学家、目录学家、文学家",
    works: [{ title: "《新序》" }, { title: "《说苑》" }, { title: "《列女传》", note: "编撰" }],
    regionKey: "guanzhong",
    placeLabel: "长安",
    locationBasis: "主要任职与校书地",
    evidenceLevel: "较高",
    evidenceNote: "应区分编撰、整理与个人原创。",
    brief: "宫廷校书与叙事文献整理的代表，使许多先秦故事得以流传。",
    sourceUrls: [
      "https://www.dpm.org.cn/lemmas/245299.html",
      "https://ctext.org/shuo-yuan/zh",
    ],
    portrait: laterPortrait("刘向"),
  },
  {
    eraId: "xin",
    name: "扬雄",
    years: "前53—18",
    identity: "辞赋家、思想家",
    works: [{ title: "《甘泉赋》" }, { title: "《长杨赋》" }, { title: "《法言》" }],
    regionKey: "southwest",
    placeLabel: "蜀郡成都",
    locationBasis: "籍贯；后入长安任职",
    evidenceLevel: "较高",
    evidenceNote: "一生活动横跨西汉末与新莽，归入本期是为了呈现新莽文学连续性。",
    brief: "以赋、哲学著述和方言研究连接西汉末与新朝。",
    sourceUrls: [
      "https://www.dpm.org.cn/lemmas/244316.html",
      "https://ctext.org/yangzi-fayan/zh",
    ],
    portrait: laterPortrait("扬雄"),
  },
  {
    eraId: "xin",
    name: "刘歆",
    years: "约前50—23",
    identity: "经学家、目录学家",
    works: [{ title: "《七略》", note: "原书已佚，内容见后世著录" }, { title: "《移书让太常博士》" }],
    regionKey: "guanzhong",
    placeLabel: "长安",
    locationBasis: "主要任职与校书地",
    evidenceLevel: "中等",
    evidenceNote: "更适合作文献整理名人；《七略》原书已佚。",
    brief: "继承刘向校书事业，形成中国早期系统目录学成果。",
    sourceUrls: ["https://ctext.org/han-shu/yi-wen-zhi/zh"],
    portrait: laterPortrait("刘歆"),
  },
  {
    eraId: "eastern-han",
    name: "班固",
    years: "32—92",
    identity: "史学家、辞赋家",
    works: [{ title: "《汉书》", note: "班氏家族积累、班固主撰，后由班昭等续成" }, { title: "《两都赋》" }],
    regionKey: "guanzhong",
    placeLabel: "扶风安陵—洛阳",
    locationBasis: "籍贯与主要任职地",
    evidenceLevel: "较高",
    evidenceNote: "《汉书》不宜简化成班固一人从零到完稿的个人作品。",
    brief: "断代史写作和京都赋的重要代表。",
    sourceUrls: [
      "https://www.britannica.com/biography/Ban-Gu",
      "https://ctext.org/han-shu/zh",
    ],
    portrait: laterPortrait("班固"),
  },
  {
    eraId: "eastern-han",
    name: "张衡",
    years: "78—139",
    identity: "科学家、辞赋家",
    works: [{ title: "《二京赋》" }, { title: "《归田赋》" }],
    regionKey: "heartland",
    placeLabel: "南阳西鄂",
    locationBasis: "籍贯",
    evidenceLevel: "较高",
    evidenceNote: "人物、籍贯和主要作品均有较稳定文献依据。",
    brief: "兼具科学与文学身份，适合在地图名人层展示跨领域创造。",
    sourceUrls: ["https://www.britannica.com/biography/Zhang-Heng"],
    portrait: laterPortrait("张衡"),
  },
  {
    eraId: "eastern-han",
    name: "蔡琰",
    years: "约177—？",
    identity: "诗人、音乐文化人物",
    works: [{ title: "《悲愤诗》", note: "五言篇归属相对稳" }, { title: "《胡笳十八拍》", note: "传统归属，学界有争议" }],
    regionKey: "heartland",
    placeLabel: "陈留圉",
    locationBasis: "籍贯",
    evidenceLevel: "中等",
    evidenceNote: "生卒年不详；《胡笳十八拍》的作者归属必须保留争议说明。",
    brief: "其离乱叙事成为汉末女性书写与音乐文学的重要文化记忆。",
    sourceUrls: ["https://www.britannica.com/biography/Cai-Yan"],
    portrait: laterPortrait("蔡琰"),
  },
  {
    eraId: "three-kingdoms",
    name: "曹操",
    years: "155—220",
    identity: "政治家、诗人",
    works: [{ title: "《观沧海》" }, { title: "《短歌行》" }, { title: "《龟虽寿》" }],
    regionKey: "heartland",
    placeLabel: "邺城",
    locationBasis: "主要政治与文学活动中心",
    evidenceLevel: "较高",
    evidenceNote: "卒于曹魏正式建国前，人物卡应标注“汉末建安”。",
    brief: "以苍劲质朴的乐府诗表达乱世、功业与生命意识。",
    sourceUrls: ["https://old.counsellor.gov.cn/wsxc/2009-10-24/10453.shtml"],
    portrait: laterPortrait("曹操"),
  },
  {
    eraId: "three-kingdoms",
    name: "曹丕",
    years: "187—226",
    identity: "曹魏君主、诗人、文学批评家",
    works: [{ title: "《燕歌行》" }, { title: "《典论·论文》" }],
    regionKey: "heartland",
    placeLabel: "邺城—洛阳",
    locationBasis: "主要政治与文学活动地",
    evidenceLevel: "较高",
    evidenceNote: "本地画像资产属于后世形象资料，不代表本人真实容貌。",
    brief: "《燕歌行》是现存较早完整七言诗，《典论·论文》则讨论文章价值与作家风格。",
    sourceUrls: ["https://ctext.org/datawiki.pl?if=gb&remap=gb&res=206184"],
    portrait: {
      src: "/rulers/cao-pi.jpg",
      alt: "曹丕后世绘像",
      reliability: "后世绘像",
      note: "沿用站内君主画像；仅作历史人物形象示意。",
    },
  },
  {
    eraId: "three-kingdoms",
    name: "曹植",
    years: "192—232",
    identity: "曹魏诗人、辞赋家",
    works: [{ title: "《洛神赋》" }, { title: "《白马篇》" }, { title: "《七哀诗》" }],
    regionKey: "heartland",
    placeLabel: "邺城—洛阳",
    locationBasis: "主要活动地",
    evidenceLevel: "较高",
    evidenceNote: "人物与诗赋集传承可据。",
    brief: "词采华茂、情感深切，是建安文学与五言诗发展的关键人物。",
    sourceUrls: [
      "https://www.dpm.org.cn/lemmas/240632.html",
      "https://ctext.org/datawiki.pl?if=gb&remap=gb&res=631026",
    ],
    portrait: laterPortrait("曹植"),
  },
  {
    eraId: "three-kingdoms",
    name: "诸葛亮",
    years: "181—234",
    identity: "蜀汉政治家、散文名家",
    works: [{ title: "《出师表》" }, { title: "《诫子书》", note: "传世文本" }],
    regionKey: "southwest",
    placeLabel: "成都—汉中",
    locationBasis: "主要任职与军政活动地",
    evidenceLevel: "中等",
    evidenceNote: "不是诗人，以表章和政论名篇进入文学层；部分篇章真伪另有讨论。",
    brief: "其表章以恳切、简净著称，将政治伦理与个人情感紧密结合。",
    sourceUrls: ["https://ctext.org/datawiki.pl?if=gb&remap=gb&res=82307"],
    portrait: laterPortrait("诸葛亮"),
  },
  {
    eraId: "jin",
    name: "陆机",
    years: "261—303",
    identity: "诗人、文学理论家",
    works: [{ title: "《文赋》" }, { title: "《赴洛道中作》" }],
    regionKey: "lower-yangtze",
    placeLabel: "吴郡",
    locationBasis: "籍贯",
    evidenceLevel: "较高",
    evidenceNote: "人物、籍贯与作品均有较稳定文献依据。",
    brief: "《文赋》系统讨论灵感、构思与语言，是中国文学理论名篇。",
    sourceUrls: ["https://www.dpm.org.cn/lemmas/240419.html"],
    portrait: laterPortrait("陆机"),
  },
  {
    eraId: "jin",
    name: "王羲之",
    years: "303—361",
    identity: "书法家、散文名篇作者",
    works: [{ title: "《兰亭集序》", note: "传世系统为摹本与刻本传统" }],
    regionKey: "lower-yangtze",
    placeLabel: "会稽山阴",
    locationBasis: "居住与主要活动地",
    evidenceLevel: "中等",
    evidenceNote: "没有可信同时代肖像；《兰亭序》原迹不存。",
    brief: "兰亭修禊将地景、聚会、书写和生命感慨凝为经典文化场景。",
    sourceUrls: [
      "https://www.dpm.org.cn/lemmas/242566.html",
      "https://www.dpm.org.cn/lemmas/240371.html",
    ],
    portrait: laterPortrait("王羲之"),
  },
  {
    eraId: "jin",
    name: "陶渊明",
    years: "约365—427",
    identity: "东晋诗人、辞赋家",
    works: [{ title: "《归园田居》" }, { title: "《饮酒》" }, { title: "《桃花源记》" }],
    regionKey: "southeast",
    placeLabel: "浔阳柴桑",
    locationBasis: "籍贯与归隐地",
    evidenceLevel: "较高",
    evidenceNote: "生年存在小幅争议，地图采用通行约数。",
    brief: "以平淡自然的语言奠定田园诗传统，并塑造“桃花源”的文化想象。",
    sourceUrls: [
      "https://www.dpm.org.cn/lemmas/241978.html",
      "https://english.scio.gov.cn/featured/chinakeywords/2024-08/30/content_117397297.htm",
    ],
    portrait: laterPortrait("陶渊明"),
  },
  {
    eraId: "sixteen-kingdoms",
    name: "鸠摩罗什",
    years: "343/344—413",
    identity: "佛经翻译家、高僧",
    works: [{ title: "《妙法莲华经》", note: "译" }, { title: "《维摩诘经》", note: "译" }, { title: "《中论》", note: "译" }],
    regionKey: "guanzhong",
    placeLabel: "后秦长安译场",
    locationBasis: "主要译经地",
    evidenceLevel: "较高",
    evidenceNote: "不是经论原作者；作品必须标“译”。",
    brief: "其典丽流畅的汉译深刻影响中国佛教、语言与文学。",
    sourceUrls: [
      "https://www.dpm.org.cn/lemmas/241529.html",
      "https://www.neac.gov.cn/seac/c103391/202211/1159594.shtml",
    ],
    portrait: laterPortrait("鸠摩罗什", "常见形象来自壁画、塑像或后世绘制，不能确认为写真。"),
  },
  {
    eraId: "sixteen-kingdoms",
    name: "王嘉",
    years: "？—390",
    identity: "志怪小说家、道士",
    works: [{ title: "《拾遗记》" }, { title: "《牵三歌谶》", note: "已佚或仅见辑录" }],
    regionKey: "northwest",
    placeLabel: "陇西安阳（今甘肃秦安）",
    locationBasis: "籍贯",
    evidenceLevel: "中等",
    evidenceNote: "生年不详；以志怪叙事名世，不应强标为诗人。",
    brief: "以奇异想象与华美叙事拓展了志怪小说的文学性。",
    sourceUrls: ["https://www.gswbj.gov.cn/a/2022/06/30/14267.html"],
    portrait: unavailablePortrait("王嘉"),
  },
  {
    eraId: "northern-southern",
    name: "谢灵运",
    years: "385—433",
    identity: "南朝诗人",
    works: [{ title: "《登池上楼》" }, { title: "《石壁精舍还湖中作》" }],
    regionKey: "lower-yangtze",
    placeLabel: "会稽—永嘉",
    locationBasis: "庄园与主要山水诗活动地",
    evidenceLevel: "较高",
    evidenceNote: "人物与主要作品较可靠。",
    brief: "推动山水诗从玄言诗中独立成熟，以精细语言重构江南山水。",
    sourceUrls: [
      "https://www.dpm.org.cn/lemmas/242839.html",
      "https://dfz.nanjing.gov.cn/gzdt/202511/t20251110_5685896.html",
    ],
    portrait: laterPortrait("谢灵运"),
  },
  {
    eraId: "northern-southern",
    name: "鲍照",
    years: "约414—466",
    identity: "南朝诗人、辞赋家",
    works: [{ title: "《拟行路难》组诗" }, { title: "《芜城赋》" }],
    regionKey: "lower-yangtze",
    placeLabel: "建康",
    locationBasis: "主要任职与文学活动地",
    evidenceLevel: "较高",
    evidenceNote: "生年采用常见约数。",
    brief: "诗风慷慨劲健，广写寒士困境、边塞和离乱。",
    sourceUrls: [
      "https://dfz.nanjing.gov.cn/gzdt/202511/t20251110_5685896.html",
      "https://www.nopss.gov.cn/n1/2020/0528/c430755-31727261.html",
    ],
    portrait: laterPortrait("鲍照"),
  },
  {
    eraId: "northern-southern",
    name: "庾信",
    years: "513—581",
    identity: "诗人、骈赋家",
    works: [{ title: "《哀江南赋》" }, { title: "《拟咏怀》组诗" }, { title: "《小园赋》" }],
    regionKey: "guanzhong",
    placeLabel: "长安",
    locationBasis: "后半生主要活动地；前期在建康",
    evidenceLevel: "较高",
    evidenceNote: "个人经历横跨南朝梁与西魏、北周。",
    brief: "把江南文采、北地离乱与身世之悲熔为南北文学汇流的代表。",
    sourceUrls: ["https://www.nopss.gov.cn/n1/2017/0329/c373410-29176436.html"],
    portrait: laterPortrait("庾信"),
  },
  {
    eraId: "northern-southern",
    name: "刘勰",
    years: "约465—约520",
    identity: "文学理论家",
    works: [{ title: "《文心雕龙》" }],
    regionKey: "lower-yangtze",
    placeLabel: "建康文化圈",
    locationBasis: "主要仕宦与著述活动区",
    evidenceLevel: "中等",
    evidenceNote: "生卒年采用约数；地图落点为主要活动文化圈。",
    brief: "系统讨论文体、创作、风格与批评，是中国古代文学理论的高峰。",
    sourceUrls: ["https://slt.shanxi.gov.cn/slwh/slls/201601/t20160103_3149675.html"],
    portrait: laterPortrait("刘勰"),
  },
  {
    eraId: "sui",
    name: "薛道衡",
    years: "540—609",
    identity: "隋代诗人",
    works: [{ title: "《昔昔盐》" }, { title: "《人日思归》" }],
    regionKey: "guanzhong",
    placeLabel: "河东汾阴",
    locationBasis: "籍贯；地图区域“关中”包含河东",
    evidenceLevel: "较高",
    evidenceNote: "人物、籍贯和代表诗作有较稳定文献依据。",
    brief: "由北朝入隋，以凝练写景和思归之情连接南北诗风。",
    sourceUrls: [
      "https://www.nopss.gov.cn/n1/2024/0228/c458484-40185327.html",
      "https://dfz.shaanxi.gov.cn/zslm/fzzlk/xbsxsz/szdylpdf/201404/P020240923621682037125.pdf",
    ],
    portrait: laterPortrait("薛道衡"),
  },
  {
    eraId: "sui",
    name: "卢思道",
    years: "531—582",
    identity: "诗人、骈文家",
    works: [{ title: "《从军行》" }, { title: "《听鸣蝉篇》" }],
    regionKey: "heartland",
    placeLabel: "范阳涿县",
    locationBasis: "籍贯；一生横跨北朝与隋初",
    evidenceLevel: "较高",
    evidenceNote: "主要创作形成于北朝至隋初，人物卡应标注跨期。",
    brief: "长篇《从军行》把边塞征戍、闺怨与时代离乱交织在一起。",
    sourceUrls: ["https://www.nopss.gov.cn/n1/2024/0228/c458484-40185327.html"],
    portrait: laterPortrait("卢思道"),
  },
  {
    eraId: "sui",
    name: "杨广",
    years: "569—618",
    identity: "隋代君主、诗人",
    works: [{ title: "《春江花月夜》" }, { title: "《野望》" }, { title: "《饮马长城窟行》" }],
    regionKey: "lower-yangtze",
    placeLabel: "江都",
    locationBasis: "主要巡幸、宫廷与诗歌活动地之一",
    evidenceLevel: "较高",
    evidenceNote: "地图落点选江都以呈现其统治后期和江南诗歌活动，不代表籍贯。",
    brief: "其诗已显露由齐梁宫体向初唐清丽声律过渡的特征。",
    sourceUrls: ["https://ctext.org/datawiki.pl?if=gb&remap=gb&res=706882"],
    portrait: {
      src: "/rulers/sui-yangdi.jpg",
      alt: "隋炀帝杨广后世绘像",
      reliability: "后世绘像",
      note: "沿用站内君主画像；仅作历史人物形象示意。",
    },
  },
  {
    eraId: "tang",
    name: "李白",
    years: "701—762",
    identity: "唐代诗人",
    works: [{ title: "《蜀道难》" }, { title: "《将进酒》" }, { title: "《早发白帝城》" }],
    regionKey: "guanzhong",
    placeLabel: "长安",
    locationBasis: "重要宫廷与文学活动地；出生地另有讨论",
    evidenceLevel: "较高",
    evidenceNote: "生平大体可据，但出生地与早年路线存在不同说法。",
    brief: "以奔放想象、强烈节奏和自由精神成为盛唐诗歌最鲜明的声音之一。",
    sourceUrls: ["https://www.dpm.org.cn/lemmas/240150.html"],
    portrait: laterPortrait("李白", "常见李白像多为宋元以后作品或近现代想象形象。"),
  },
  {
    eraId: "tang",
    name: "杜甫",
    years: "712—770",
    identity: "唐代诗人",
    works: [{ title: "《春望》" }, { title: "《三吏》《三别》" }, { title: "《登高》" }],
    regionKey: "southwest",
    placeLabel: "成都草堂",
    locationBasis: "重要寓居与创作地",
    evidenceLevel: "较高",
    evidenceNote: "地图选择成都而非籍贯巩县，用于连接具体文化地标。",
    brief: "以深沉现实关怀记录安史乱离，诗作因而有“诗史”之称。",
    sourceUrls: [
      "https://www.britannica.com/biography/Du-Fu",
      "https://en.chnmuseum.cn/Portals/0/web/exhibition/exhibitions/161120Chines-Epic/",
    ],
    portrait: laterPortrait("杜甫", "常见杜甫像属于后世绘像系统，并非同时代写真。"),
  },
  {
    eraId: "tang",
    name: "王维",
    years: "701—761",
    identity: "诗人、画家",
    works: [{ title: "《山居秋暝》" }, { title: "《使至塞上》" }, { title: "《辋川集》" }],
    regionKey: "guanzhong",
    placeLabel: "蓝田辋川",
    locationBasis: "别业与山水诗重要创作地",
    evidenceLevel: "较高",
    evidenceNote: "人物与主要作品可据；现存所谓王维画作多涉及归属问题。",
    brief: "将山水、音乐、禅意与绘画感融入精炼诗境。",
    sourceUrls: ["https://www.dpm.org.cn/lemmas/242108.html"],
    portrait: laterPortrait("王维"),
  },
  {
    eraId: "tang",
    name: "白居易",
    years: "772—846",
    identity: "唐代诗人",
    works: [{ title: "《长恨歌》" }, { title: "《琵琶行》" }, { title: "《卖炭翁》" }],
    regionKey: "lower-yangtze",
    placeLabel: "杭州—苏州",
    locationBasis: "重要任职与诗歌活动地",
    evidenceLevel: "较高",
    evidenceNote: "地图以江南任所呈现其文化影响，不代表出生地。",
    brief: "主张文章合为时而著，以平易语言兼写民生、爱情与个人感怀。",
    sourceUrls: ["https://www.dpm.org.cn/lemmas/245549.html"],
    portrait: laterPortrait("白居易"),
  },
  {
    eraId: "five-dynasties",
    name: "李煜",
    years: "937—978",
    identity: "南唐君主、词人",
    works: [{ title: "《虞美人·春花秋月何时了》" }, { title: "《浪淘沙令·帘外雨潺潺》" }, { title: "《相见欢·无言独上西楼》" }],
    regionKey: "lower-yangtze",
    placeLabel: "金陵",
    locationBasis: "南唐都城与主要创作地",
    evidenceLevel: "较高",
    evidenceNote: "常见人物形象为后世创作；作品文本传承较稳定。",
    brief: "亡国前后的人生巨变扩展了词的情感深度和表达疆域。",
    sourceUrls: [
      "https://news.nankai.edu.cn/mtnk/system/2024/03/23/030060572.shtml",
      "https://www.chinafilm.gov.cn/dybalxgs/202210/t20221013_569339.html",
    ],
    portrait: laterPortrait("李煜"),
  },
  {
    eraId: "five-dynasties",
    name: "冯延巳",
    years: "903—960",
    identity: "南唐词人、官员",
    works: [{ title: "《鹊踏枝·谁道闲情抛掷久》" }, { title: "《谒金门·风乍起》" }, { title: "《阳春集》" }],
    regionKey: "lower-yangtze",
    placeLabel: "金陵",
    locationBasis: "主要任职与文学活动地",
    evidenceLevel: "中等",
    evidenceNote: "《阳春集》存在混入他人作品等文本归属问题。",
    brief: "以缠绵深婉的小词承接花间传统，并影响北宋词风。",
    sourceUrls: [
      "https://ctext.org/datawiki.pl?if=gb&remap=gb&res=122091",
      "https://news.nankai.edu.cn/mtnk/system/2024/03/23/030060572.shtml",
    ],
    portrait: laterPortrait("冯延巳"),
  },
  {
    eraId: "five-dynasties",
    name: "韦庄",
    years: "约836—910",
    identity: "诗人、词人、前蜀官员",
    works: [{ title: "《秦妇吟》" }, { title: "《菩萨蛮·人人尽说江南好》" }, { title: "《浣花集》" }],
    regionKey: "southwest",
    placeLabel: "成都",
    locationBasis: "晚年主要任职与文学活动地",
    evidenceLevel: "较高",
    evidenceNote: "生年存在不同说法，采用常见约数；一生横跨晚唐与五代。",
    brief: "从长篇乱离叙事到花间词，连接晚唐诗歌与前蜀词坛。",
    sourceUrls: ["https://news.nankai.edu.cn/mtnk/system/2024/03/23/030060572.shtml"],
    portrait: laterPortrait("韦庄"),
  },
  {
    eraId: "liao",
    name: "耶律倍",
    years: "899—937",
    identity: "契丹贵族、诗人、画家",
    works: [{ title: "《海上诗》", note: "传世短诗，题名与文本据后世记载" }],
    regionKey: "northeast",
    placeLabel: "辽上京—东丹国",
    locationBasis: "主要政治与文化活动区域",
    evidenceLevel: "中等",
    evidenceNote: "诗作传承依靠后世史籍，画像亦不可视为本人写真。",
    brief: "精通汉文典籍并能诗善画，是辽初跨文化贵族的代表。",
    sourceUrls: [
      "https://old.counsellor.gov.cn/wsxc/2009-10-24/10453.shtml",
      "https://www.neac.gov.cn/seac/c103391/202212/1159876.shtml",
    ],
    portrait: laterPortrait("耶律倍"),
  },
  {
    eraId: "liao",
    name: "萧观音",
    years: "1040—1075",
    identity: "辽代皇后、诗人",
    works: [{ title: "《回心院》组诗" }, { title: "《怀古》" }, { title: "《伏虎林应制》" }],
    regionKey: "northeast",
    placeLabel: "辽上京—中京宫廷圈",
    locationBasis: "主要宫廷活动区域",
    evidenceLevel: "中等",
    evidenceNote: "生平与作品主要见辽代史籍及后世辑录，具体创作地多不可考。",
    brief: "以宫廷女性视角留下情感细密、声律清丽的诗歌。",
    sourceUrls: ["https://old.counsellor.gov.cn/wsxc/2009-10-24/10453.shtml"],
    portrait: laterPortrait("萧观音"),
  },
  {
    eraId: "liao",
    name: "耶律洪基",
    years: "1032—1101",
    identity: "辽道宗、诗人",
    works: [{ title: "《题李俨黄菊赋》" }, { title: "《清宁集》", note: "已佚" }],
    regionKey: "northeast",
    placeLabel: "辽代宫廷中心",
    locationBasis: "主要统治与宫廷文学活动区",
    evidenceLevel: "中等",
    evidenceNote: "诗集已佚，现存作品数量有限。",
    brief: "辽代宫廷汉诗创作的代表之一，可与契丹本族文学并置观看。",
    sourceUrls: ["https://old.counsellor.gov.cn/wsxc/2009-10-24/10453.shtml"],
    portrait: laterPortrait("耶律洪基"),
  },
  {
    eraId: "northern-song",
    name: "欧阳修",
    years: "1007—1072",
    identity: "文学家、史学家",
    works: [{ title: "《醉翁亭记》" }, { title: "《秋声赋》" }, { title: "《蝶恋花·庭院深深深几许》" }],
    regionKey: "heartland",
    placeLabel: "汴京—滁州",
    locationBasis: "主要仕宦与文学活动地",
    evidenceLevel: "较高",
    evidenceNote: "籍贯为庐陵，地图以影响更直观的任职活动地落点。",
    brief: "推动北宋古文革新，并以奖掖后进形成影响深远的文人网络。",
    sourceUrls: ["https://www.dpm.org.cn/lemmas/240594.html"],
    portrait: laterPortrait("欧阳修"),
  },
  {
    eraId: "northern-song",
    name: "苏轼",
    years: "1037—1101",
    identity: "文学家、书画家",
    works: [{ title: "《赤壁赋》" }, { title: "《念奴娇·赤壁怀古》" }, { title: "《水调歌头·明月几时有》" }],
    regionKey: "southwest",
    placeLabel: "眉州眉山",
    locationBasis: "籍贯；一生仕履遍及多地",
    evidenceLevel: "较高",
    evidenceNote: "常见东坡像多为后世绘像；其书迹、文集则有可靠传承。",
    brief: "以开放旷达的心灵贯通诗、词、文、书画，成为北宋文化的综合性高峰。",
    sourceUrls: [
      "https://www.dpm.org.cn/lemmas/242068.html",
      "https://www.dpm.org.cn/auditions/exhibition/detail/254446.html",
    ],
    portrait: laterPortrait("苏轼", "故宫展出的东坡主题绘像多为后世作品，可作形象史材料而非写真。"),
  },
  {
    eraId: "northern-song",
    name: "王安石",
    years: "1021—1086",
    identity: "政治家、文学家",
    works: [{ title: "《泊船瓜洲》" }, { title: "《登飞来峰》" }, { title: "《游褒禅山记》" }],
    regionKey: "southeast",
    placeLabel: "抚州临川",
    locationBasis: "籍贯",
    evidenceLevel: "较高",
    evidenceNote: "人物与作品传承稳定。",
    brief: "政论峭拔、晚年诗风精炼，在改革家身份之外展现深厚文学创造。",
    sourceUrls: ["https://www.dpm.org.cn/lemmas/243269.html"],
    portrait: laterPortrait("王安石"),
  },
  {
    eraId: "northern-song",
    name: "李清照",
    years: "1084—约1155",
    identity: "词人、金石学家",
    works: [{ title: "《如梦令·常记溪亭日暮》" }, { title: "《醉花阴·薄雾浓云愁永昼》" }, { title: "《声声慢·寻寻觅觅》", note: "南渡后作品" }],
    regionKey: "heartland",
    placeLabel: "齐州章丘",
    locationBasis: "籍贯；后南渡江南",
    evidenceLevel: "较高",
    evidenceNote: "生平横跨北宋与南宋，归入北宋但作品卡标出南渡后的变化。",
    brief: "词风由早年的明快清丽转向南渡后的沉郁哀痛，个人生命与时代巨变交叠。",
    sourceUrls: ["https://www.britannica.com/biography/Li-Qingzhao"],
    portrait: laterPortrait("李清照"),
  },
  {
    eraId: "western-xia",
    name: "骨勒茂才",
    years: "12世纪后期",
    identity: "西夏学者、辞书编纂者",
    works: [{ title: "《番汉合时掌中珠》" }],
    regionKey: "northwest",
    placeLabel: "兴庆府文化圈",
    locationBasis: "成书政权与语言文化中心；个人生平地望不详",
    evidenceLevel: "中等",
    evidenceNote: "著作与姓名可据，但个人生平资料非常有限。",
    brief: "以西夏文、汉文双语辞书促进语言学习，是西夏多民族文字交流的可核名人。",
    sourceUrls: ["https://www.neac.gov.cn/seac/c103391/202301/1160242.shtml"],
    portrait: unavailablePortrait("骨勒茂才"),
  },
  {
    eraId: "western-xia",
    name: "鲜卑宝源",
    years: "西夏时期",
    identity: "西夏国师、文学作者",
    works: [{ title: "《贤智集》" }],
    regionKey: "northwest",
    placeLabel: "西夏河西—兴庆文化圈",
    locationBasis: "作品所属文化区域；个人行迹资料有限",
    evidenceLevel: "谨慎",
    evidenceNote: "可核到作者与书名，但生卒、籍贯和具体写作地点资料不足。",
    brief: "《贤智集》呈现西夏文学吸收中原句式、用韵与伦理表达的面貌。",
    sourceUrls: ["https://www.nopss.gov.cn/n1/2025/1217/c219544-40626303.html"],
    portrait: unavailablePortrait("鲜卑宝源"),
  },
  {
    eraId: "western-xia",
    name: "《敕牌赞歌》作者（佚名）",
    years: "西夏时期",
    identity: "西夏文诗歌佚名作者",
    works: [{ title: "《敕牌赞歌》", note: "作者姓名不详，今见译文" }],
    regionKey: "northwest",
    placeLabel: "西夏驿传与宫廷系统",
    locationBasis: "文物制度与作品语境，非个人籍贯",
    evidenceLevel: "中等",
    evidenceNote: "诗歌可据，作者身份、具体年代与地点不可考。",
    brief: "以第一人称赞颂敕牌的权威和驿传功能，是西夏文实物诗歌的独特节点。",
    sourceUrls: ["https://www.chnmuseum.cn/yj/xscg/xslw/201812/t20181224_33227.shtml"],
    portrait: unavailablePortrait("《敕牌赞歌》作者", "匿名作者不生成个人肖像，界面宜使用西夏文或敕牌纹样占位。"),
  },
  {
    eraId: "jin-dynasty",
    name: "元好问",
    years: "1190—1257",
    identity: "诗人、词人、文献编纂者",
    works: [{ title: "《论诗三十首》" }, { title: "《摸鱼儿·雁丘词》" }, { title: "《中州集》", note: "编纂" }],
    regionKey: "guanzhong",
    placeLabel: "太原秀容（今山西忻州）",
    locationBasis: "籍贯；地图区域“关中”包含河东",
    evidenceLevel: "较高",
    evidenceNote: "一生横跨金亡前后；地图归入金代以体现其核心文学身份。",
    brief: "以“丧乱诗”记录金末巨变，并保存一代诗人文献。",
    sourceUrls: [
      "https://www.neac.gov.cn/seac/c103391/202212/1159888.shtml",
      "https://www.pingcheng.gov.cn/pcqrmzfz/sxyw/202504/2cbf46660cf34a66a831a7230246423f.shtml",
    ],
    portrait: laterPortrait("元好问"),
  },
  {
    eraId: "jin-dynasty",
    name: "赵秉文",
    years: "1159—1232",
    identity: "文学家、书法家",
    works: [{ title: "《滏水集》" }, { title: "《和渊明饮酒二十首》" }],
    regionKey: "heartland",
    placeLabel: "磁州滏阳",
    locationBasis: "籍贯",
    evidenceLevel: "较高",
    evidenceNote: "故宫词条对生卒未作确定，年份采用学界通行说。",
    brief: "金代中后期文坛领袖之一，诗文、书法兼擅。",
    sourceUrls: ["https://www.dpm.org.cn/lemmas/242671.html"],
    portrait: laterPortrait("赵秉文"),
  },
  {
    eraId: "jin-dynasty",
    name: "完颜亮",
    years: "1122—1161",
    identity: "金代君主、词人",
    works: [{ title: "《念奴娇·天丁震怒》" }, { title: "《喜迁莺·旌麾初举》" }],
    regionKey: "heartland",
    placeLabel: "中都—汴京政治圈",
    locationBasis: "主要统治与文学活动区",
    evidenceLevel: "中等",
    evidenceNote: "作品多赖南宋文献保存，需把文学评价与政治评价分开。",
    brief: "其词呈现强烈权力意志，是理解宋金对峙中文学互见的特殊样本。",
    sourceUrls: ["https://www.nopss.gov.cn/GB/219506/219508/219525/14600713.html"],
    portrait: laterPortrait("完颜亮"),
  },
  {
    eraId: "southern-song",
    name: "辛弃疾",
    years: "1140—1207",
    identity: "词人、官员",
    works: [{ title: "《破阵子·为陈同甫赋壮词以寄之》" }, { title: "《永遇乐·京口北固亭怀古》" }, { title: "《青玉案·元夕》" }],
    regionKey: "southeast",
    placeLabel: "江西上饶—铅山",
    locationBasis: "长期退居与重要创作地；出生于济南",
    evidenceLevel: "较高",
    evidenceNote: "生平跨金境出生与南宋仕宦，地图以南方创作地落点。",
    brief: "把恢复理想、英雄失意、田园生活与典故学养熔入豪放词。",
    sourceUrls: [
      "https://www.nopss.gov.cn/GB/219506/219508/219525/14600713.html",
      "https://www.britannica.com/biography/Xin-Qiji",
    ],
    portrait: laterPortrait("辛弃疾"),
  },
  {
    eraId: "southern-song",
    name: "陆游",
    years: "1125—1210",
    identity: "诗人、词人",
    works: [{ title: "《示儿》" }, { title: "《书愤》" }, { title: "《钗头凤·红酥手》" }],
    regionKey: "lower-yangtze",
    placeLabel: "山阴（今绍兴）",
    locationBasis: "籍贯、晚年居地与重要创作地",
    evidenceLevel: "较高",
    evidenceNote: "人物、地望与诗文传承稳定。",
    brief: "以万余首诗记录报国理想、乡居日常、爱情与时代创痛。",
    sourceUrls: [
      "https://www.dpm.org.cn/journal_detail/249066.html",
      "https://www.britannica.com/biography/Lu-You",
    ],
    portrait: laterPortrait("陆游"),
  },
  {
    eraId: "southern-song",
    name: "杨万里",
    years: "1127—1206",
    identity: "诗人",
    works: [{ title: "《小池》" }, { title: "《晓出净慈寺送林子方》" }, { title: "《过松源晨炊漆公店》" }],
    regionKey: "southeast",
    placeLabel: "吉州吉水",
    locationBasis: "籍贯与主要乡居地",
    evidenceLevel: "较高",
    evidenceNote: "人物与作品传承稳定。",
    brief: "“诚斋体”从日常细节捕捉鲜活诗意，语言浅近而转折灵动。",
    sourceUrls: ["https://www.britannica.com/biography/Yang-Wanli"],
    portrait: laterPortrait("杨万里"),
  },
  {
    eraId: "southern-song",
    name: "姜夔",
    years: "约1155—约1221",
    identity: "词人、音乐家",
    works: [{ title: "《扬州慢·淮左名都》" }, { title: "《暗香》" }, { title: "《疏影》" }],
    regionKey: "lower-yangtze",
    placeLabel: "杭州—湖州",
    locationBasis: "长期客居与主要交游创作区",
    evidenceLevel: "中等",
    evidenceNote: "生卒年多取约数，行迹流动，地图落点是主要活动文化圈。",
    brief: "兼通音律，自度曲词清空雅正，又沉淀故国与身世之感。",
    sourceUrls: ["https://ctext.org/searchbooks.pl?author=%E5%A7%9C%E5%A4%94&if=gb&remap=gb"],
    portrait: laterPortrait("姜夔"),
  },
  {
    eraId: "yuan",
    name: "关汉卿",
    years: "约1220—约1300",
    identity: "元杂剧作家、散曲家",
    works: [{ title: "《窦娥冤》" }, { title: "《救风尘》" }, { title: "《望江亭》" }],
    regionKey: "heartland",
    placeLabel: "大都戏曲圈",
    locationBasis: "主要活动地；籍贯有解州、祁州、大都等说",
    evidenceLevel: "中等",
    evidenceNote: "生卒、籍贯与部分剧目归属存在讨论。",
    brief: "以强烈戏剧冲突和鲜活口语塑造普通人的抗争，是元曲最具代表性的作家。",
    sourceUrls: ["https://en.chnmuseum.cn/Portals/0/web/exhibition/exhibitions/161120Chines-Epic/"],
    portrait: laterPortrait("关汉卿"),
  },
  {
    eraId: "yuan",
    name: "马致远",
    years: "约1250—1321以后",
    identity: "杂剧作家、散曲家",
    works: [{ title: "《天净沙·秋思》" }, { title: "《汉宫秋》" }, { title: "《荐福碑》" }],
    regionKey: "heartland",
    placeLabel: "大都",
    locationBasis: "传统主要活动地",
    evidenceLevel: "中等",
    evidenceNote: "生卒年份和部分行迹资料不完整。",
    brief: "以凝练意象写尽羁旅秋思，并在杂剧中重构历史与士人命运。",
    sourceUrls: ["https://www.dpm.org.cn/Uploads/File/2020/04/22/u5ea01965b7ec8.pdf"],
    portrait: laterPortrait("马致远"),
  },
  {
    eraId: "yuan",
    name: "王实甫",
    years: "约1260—约1336",
    identity: "元杂剧作家",
    works: [{ title: "《西厢记》" }],
    regionKey: "heartland",
    placeLabel: "大都戏曲圈",
    locationBasis: "传统活动地；生平资料极少",
    evidenceLevel: "谨慎",
    evidenceNote: "生平、籍贯和生卒年均缺乏坚实材料，地图仅作剧作文化圈落点。",
    brief: "《西厢记》以精密结构、优美曲词与爱情主题成为元杂剧经典。",
    sourceUrls: ["https://www.dpm.org.cn/Uploads/File/2020/04/22/u5ea01965b7ec8.pdf"],
    portrait: laterPortrait("王实甫", "生平材料极少，常见人物像多为近现代戏曲文化想象。"),
  },
  {
    eraId: "yuan",
    name: "萨都剌",
    years: "约1272—约1355",
    identity: "元代诗人、词人",
    works: [{ title: "《念奴娇·登石头城次东坡韵》" }, { title: "《满江红·金陵怀古》" }, { title: "《雁门集》" }],
    regionKey: "guanzhong",
    placeLabel: "雁门",
    locationBasis: "籍贯；地图区域“关中”包含河东",
    evidenceLevel: "中等",
    evidenceNote: "生卒年采用常见约数；仕履遍及南北。",
    brief: "以多民族身份和广阔行旅经验书写山河、怀古与民生。",
    sourceUrls: ["https://www.neac.gov.cn/seac/xwzx/202408/1175405.shtml"],
    portrait: laterPortrait("萨都剌"),
  },
  {
    eraId: "ming",
    name: "高启",
    years: "1336—1374",
    identity: "明初诗人",
    works: [{ title: "《登金陵雨花台望大江》" }, { title: "《青丘子歌》" }, { title: "《梅花九首》" }],
    regionKey: "lower-yangtze",
    placeLabel: "苏州",
    locationBasis: "籍贯与主要创作地",
    evidenceLevel: "较高",
    evidenceNote: "人物与作品有较稳定传承。",
    brief: "承接元末江南诗风，又以雄健清新的格调成为明初诗坛代表。",
    sourceUrls: ["https://sxyk.henu.edu.cn/info/1090/1331.htm"],
    portrait: laterPortrait("高启"),
  },
  {
    eraId: "ming",
    name: "唐寅",
    years: "1470—1523",
    identity: "诗人、书画家",
    works: [{ title: "《桃花庵歌》" }, { title: "《把酒对月歌》" }, { title: "《六如居士全集》" }],
    regionKey: "lower-yangtze",
    placeLabel: "苏州",
    locationBasis: "籍贯与主要生活地",
    evidenceLevel: "较高",
    evidenceNote: "民间传说与影视形象很多，人物卡应以可核生平为准。",
    brief: "诗、书、画交织的江南文人典型，真实人生远比“风流才子”标签复杂。",
    sourceUrls: ["https://www.dpm.org.cn/lemmas/242652.html"],
    portrait: laterPortrait("唐寅", "传世题材中虽有唐寅形象，仍不宜无依据宣称为本人写真。"),
  },
  {
    eraId: "ming",
    name: "杨慎",
    years: "1488—1559",
    identity: "文学家、学者",
    works: [{ title: "《临江仙·滚滚长江东逝水》" }, { title: "《升庵集》" }, { title: "《滇海曲》" }],
    regionKey: "southwest",
    placeLabel: "云南谪居地—新都",
    locationBasis: "长期流放与故里文化区域",
    evidenceLevel: "较高",
    evidenceNote: "地图落点强调其云南流放经历；出生于北京、祖籍四川新都。",
    brief: "博学广涉，长期谪居西南使其诗文充满山川行旅与历史兴亡感。",
    sourceUrls: ["https://ctext.org/datawiki.pl?if=gb&remap=gb&res=532045"],
    portrait: laterPortrait("杨慎"),
  },
  {
    eraId: "ming",
    name: "徐渭",
    years: "1521—1593",
    identity: "诗人、戏曲家、书画家",
    works: [{ title: "《四声猿》" }, { title: "《南词叙录》" }, { title: "《题墨葡萄诗》" }],
    regionKey: "lower-yangtze",
    placeLabel: "山阴（今绍兴）",
    locationBasis: "籍贯与主要生活地",
    evidenceLevel: "较高",
    evidenceNote: "人物和著述可靠；后世“狂人”叙事需避免猎奇化。",
    brief: "把奔放不羁的精神贯穿诗文、戏曲、书法和大写意绘画。",
    sourceUrls: ["https://www.dpm.org.cn/lemmas/243347.html"],
    portrait: laterPortrait("徐渭"),
  },
  {
    eraId: "qing",
    name: "纳兰性德",
    years: "1654—1685",
    identity: "清代词人",
    works: [{ title: "《木兰花令·拟古决绝词》" }, { title: "《长相思·山一程》" }, { title: "《饮水词》" }],
    regionKey: "heartland",
    placeLabel: "北京",
    locationBasis: "出生、任职与主要生活地",
    evidenceLevel: "较高",
    evidenceNote: "年份依故宫词条；常见清装像未必有可靠肖像来源。",
    brief: "以清真深婉的小令书写爱情、悼亡、扈从与边塞经验。",
    sourceUrls: ["https://www.dpm.org.cn/lemmas/244753.html"],
    portrait: laterPortrait("纳兰性德"),
  },
  {
    eraId: "qing",
    name: "袁枚",
    years: "1716—1797",
    identity: "诗人、文学批评家",
    works: [{ title: "《随园诗话》" }, { title: "《苔》" }, { title: "《祭妹文》" }],
    regionKey: "lower-yangtze",
    placeLabel: "南京随园",
    locationBasis: "长期居住、著述与文人交游地",
    evidenceLevel: "较高",
    evidenceNote: "人物与随园地望可据；常见画像仍需逐件核验来源与年代。",
    brief: "倡导“性灵”诗论，随园也成为清代重要的诗歌交游空间。",
    sourceUrls: ["https://www.britannica.com/biography/Yuan-Mei"],
    portrait: laterPortrait("袁枚"),
  },
  {
    eraId: "qing",
    name: "曹雪芹",
    years: "约1715—约1763",
    identity: "小说家、诗人",
    works: [{ title: "《红楼梦》", note: "后四十回作者与成书问题另有讨论" }],
    regionKey: "heartland",
    placeLabel: "北京西郊",
    locationBasis: "晚年生活与主要创作地",
    evidenceLevel: "中等",
    evidenceNote: "生卒、家世若干细节及《红楼梦》成书过程仍有学术争议。",
    brief: "以家族兴衰、女性群像和诗性语言创造中国古典小说高峰。",
    sourceUrls: ["https://www.dpm.org.cn/lemmas/245565.html"],
    portrait: unavailablePortrait("曹雪芹", "没有公认可确证为曹雪芹本人的传世画像，常见形象多属后世想象。"),
  },
  {
    eraId: "qing",
    name: "龚自珍",
    years: "1792—1841",
    identity: "诗人、思想家",
    works: [{ title: "《己亥杂诗》" }, { title: "《病梅馆记》" }, { title: "《尊隐》" }],
    regionKey: "lower-yangtze",
    placeLabel: "杭州仁和",
    locationBasis: "籍贯；后长期在北京任职",
    evidenceLevel: "较高",
    evidenceNote: "人物与作品传承稳定，地图以籍贯落点。",
    brief: "以敏锐历史危机感、改革意识和瑰丽语言开启近代诗文新声。",
    sourceUrls: ["https://www.britannica.com/biography/Gong-Zizhen"],
    portrait: laterPortrait("龚自珍"),
  },
] satisfies LiteraryFigure[];

export const literaryFiguresByEra = literaryFigures.reduce<Record<string, LiteraryFigure[]>>((grouped, figure) => {
  (grouped[figure.eraId] ??= []).push(figure);
  return grouped;
}, {});

export const literaryFigureStats = {
  total: literaryFigures.length,
  eraCount: Object.keys(literaryFiguresByEra).length,
  withPortraitCount: literaryFigures.filter((figure) => Boolean(figure.portrait.src)).length,
  cautiousCount: literaryFigures.filter((figure) => figure.evidenceLevel === "谨慎").length,
  byEra: Object.fromEntries(Object.entries(literaryFiguresByEra).map(([eraId, figures]) => [eraId, figures.length])),
} as const;
